# Generated by Django 5.1.7 on 2025-06-23 17:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="garchresult",
            name="summary",
            field=models.CharField(blank=True, null=True),
        ),
    ]
