# Generated by Django 5.1.7 on 2025-06-28 12:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "garch",
            "0005_rename_model_fit_result_ljung_box_test_results_garchresult_model_fit_ljung_box_test_results",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="garchresult",
            name="p_mean_equation_lags",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="garchresult",
            name="q_variance_equation_lags",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
