# Generated by Django 5.1.7 on 2025-06-28 12:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0006_garchresult_p_mean_equation_lags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garchresult",
            name="p_mean_equation_lags",
            field=models.IntegerField(default=0),
        ),
    ]
