# Generated by Django 5.1.7 on 2025-06-29 14:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0008_garchresult_model_result_conditional_volatility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garchresult",
            name="acf_lags",
            field=models.IntegerField(default=36),
        ),
    ]
