# Generated by Django 5.1.7 on 2025-06-29 15:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0009_garchresult_acf_lags"),
    ]

    operations = [
        migrations.AddField(
            model_name="garchresult",
            name="tests_lags",
            field=models.IntegerField(default=5),
        ),
    ]
