# Generated by Django 5.1.7 on 2025-07-06 09:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0010_garchresult_tests_lags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garchresult",
            name="test_mae",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="test_mape",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="test_mse",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="test_r_2",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="test_rmse",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="val_mae",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="val_mape",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="val_mse",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="val_r_2",
        ),
        migrations.RemoveField(
            model_name="garchresult",
            name="val_rmse",
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_mae",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Mean Absolute Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_mape",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Mean Absolute Percentage Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_mse",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Mean Squared Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_r2",
            field=models.FloatField(
                blank=True,
                help_text="Test set: R-squared score for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_rmse",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Root Mean Squared Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_vol_mae",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Mean Absolute Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_vol_mse",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Mean Squared Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_vol_qlike",
            field=models.FloatField(
                blank=True,
                help_text="Test set: QLIKE loss between predicted variance and squared returns (lower is better).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="test_vol_rmse",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Root Mean Squared Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_mae",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Mean Absolute Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_mape",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Mean Absolute Percentage Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_mse",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Mean Squared Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_r2",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: R-squared score for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_rmse",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Root Mean Squared Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_vol_mae",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Mean Absolute Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_vol_mse",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Mean Squared Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_vol_qlike",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: QLIKE loss between predicted variance and squared returns (lower is better).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_vol_rmse",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Root Mean Squared Error between predicted variance and squared returns.",
                null=True,
            ),
        ),
    ]
