# Generated by Django 5.1.7 on 2025-07-27 11:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0012_remove_garchresult_test_predictions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garchresult",
            name="test_mean_smape",
            field=models.FloatField(
                blank=True,
                help_text="Test set: Symmetric Mean Absolute Percentage Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="garchresult",
            name="val_mean_smape",
            field=models.FloatField(
                blank=True,
                help_text="Validation set: Symmetric Mean Absolute Percentage Error for predicted vs. actual returns.",
                null=True,
            ),
        ),
    ]
