# Generated by Django 5.1.7 on 2025-09-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garch", "0013_garchresult_test_mean_smape_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garchresult",
            old_name="p_mean_equation_lags",
            new_name="arch_order",
        ),
        migrations.RenameField(
            model_name="garchresult",
            old_name="q_variance_equation_lags",
            new_name="garch_order",
        ),
    ]
