# Generated by Django 5.1.7 on 2025-05-03 07:33

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preprocessing", "0004_alter_dataupload_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinearRegressionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preprocessing.data",
                    ),
                ),
            ],
        ),
    ]
