# Generated by Django 5.1.7 on 2025-05-03 10:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0001_initial"),
        ("preprocessing", "0004_alter_dataupload_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinearRegressionTimeSeriesResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_column", models.CharField()),
                ("predictions", models.JSONField(blank=True, null=True)),
                ("r_2", models.FloatField(blank=True, help_text="R2 score", null=True)),
                (
                    "mse",
                    models.FloatField(
                        blank=True, help_text="Mean squared error", null=True
                    ),
                ),
                (
                    "mae",
                    models.FloatField(
                        blank=True, help_text="Mean absolute error", null=True
                    ),
                ),
                (
                    "rmse",
                    models.FloatField(
                        blank=True, help_text="Root mean square error", null=True
                    ),
                ),
                (
                    "mape",
                    models.FloatField(
                        blank=True,
                        help_text="Mean absolute percentage error",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preprocessing.data",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LinearRegressionResult",
        ),
    ]
