# Generated by Django 5.1.7 on 2025-05-03 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0002_linearregressiontimeseriesresult_and_more"),
        ("preprocessing", "0004_alter_dataupload_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="linearregressiontimeseriesresult",
            name="data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linear_regression_timeseries_results",
                to="preprocessing.data",
            ),
        ),
    ]
