# Generated by Django 5.1.7 on 2025-05-03 12:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "linear_regression",
            "0003_linearregressiontimeseriesresult_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="lag_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
