# Generated by Django 5.1.7 on 2025-05-04 10:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0004_linearregressiontimeseriesresult_lag_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="model_type",
            field=models.CharField(default="linear_regression"),
            preserve_default=False,
        ),
    ]
