# Generated by Django 5.1.7 on 2025-05-04 11:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0005_linearregressiontimeseriesresult_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="max_tree_depth",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
