# Generated by Django 5.1.7 on 2025-05-29 13:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0006_linearregressiontimeseriesresult_max_tree_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="forecast_horizon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
