# Generated by Django 5.1.7 on 2025-05-29 14:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0007_linearregressiontimeseriesresult_forecast_horizon"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="forecast",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
