# Generated by Django 5.1.7 on 2025-05-29 16:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0008_linearregressiontimeseriesresult_forecast"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="intercept",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="slope",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
