# Generated by Django 5.1.7 on 2025-06-08 11:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "linear_regression",
            "0009_linearregressiontimeseriesresult_intercept_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="test_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="train_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="validation_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
