# Generated by Django 5.1.7 on 2025-06-11 13:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "linear_regression",
            "0012_remove_linearregressiontimeseriesresult_validation_predictions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="train_values",
            field=models.JSONField(blank=True, help_text="Train data set", null=True),
        ),
    ]
