# Generated by Django 5.1.7 on 2025-08-31 09:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("linear_regression", "0013_linearregressiontimeseriesresult_train_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="test_tree_levels",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="val_tree_levels",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
