# Generated by Django 5.1.7 on 2025-09-01 17:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "linear_regression",
            "0014_linearregressiontimeseriesresult_test_tree_levels_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="linearregressiontimeseriesresult",
            name="target_mode",
            field=models.CharField(blank=True, default="delta", null=True),
        ),
    ]
