# Generated by Django 5.1.7 on 2025-03-22 14:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocessing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="data_columns",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Found DataFrame columns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="data_index",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="DataFrame indexes defined by the user. Must match possible column names.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional information about the data source.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="name",
            field=models.CharField(
                help_text="Name of the data source.", max_length=256
            ),
        ),
    ]
