# Generated by Django 5.1.7 on 2025-04-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preprocessing", "0002_data_data_columns_data_data_index_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataStatistics",
        ),
    ]
