# Generated by Django 5.1.7 on 2025-07-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preprocessing", "0005_testresult"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestResult",
            new_name="DataTestResult",
        ),
    ]
