# Generated by Django 5.1.7 on 2025-07-09 15:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocessing", "0006_rename_testresult_datatestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatestresult",
            name="differentiate_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datatestresult",
            name="max_augmentation_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datatestresult",
            name="target_column",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datatestresult",
            name="test_version",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datatestresult",
            name="test_type",
            field=models.CharField(blank=True, null=True),
        ),
    ]
