# Generated by Django 5.1.7 on 2025-04-14 17:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional information about the integration API.",
                null=True,
            ),
        ),
    ]
